---
apiVersion: v1
kind: Namespace
metadata:
  name: staging

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: staging
  name: test-claim
spec:
  storageClassName: efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs-pvc
          mountPath: "/data"
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: test-claim
